UPDATE `quest_offer_reward` SET `RewardText` = 'You\'ve been busy!  I can\'t wait to cook up that wolf meat...$B$BI have some things here you might want - take your pick!' WHERE `ID` = 33;

UPDATE `quest_offer_reward` SET `RewardText` = 'You did it, $g lad : lass;! We\'ll get those copper bars onto the pile and put them to good use making the war materiel right away. It\'s the efforts of people like you that make me proud to serve the Alliance. Good work, soldier!$B$BAnd if you should happen to come across more copper bars, make sure that they find their way to me.' WHERE `ID` = 8492;
UPDATE `quest_offer_reward` SET `RewardText` = 'Must be a cold day in the Burning Steppes. Look here, it\'s $N, and $g he\'s : she\'s; brought me a gift. Twenty iron bars! Just what I always wanted.$B$BIn all seriousness though, thank you, $N. You\'re a credit to yourself and the Alliance. Now get back out there and bring in more stuff for the war effort!' WHERE `ID` = 8495;
UPDATE `quest_offer_reward` SET `RewardText` = 'Golly, that sure is a lot of medium leather that you\'ve brought round, $g sir : ma\'am;! I\'m gonna make sure that all of that gets put to proper use, yes indeed. With your help we\'ll have filled our estimation for medium leather in no time!$B$BThanks, $N!' WHERE `ID` = 8514;
UPDATE `quest_offer_reward` SET `RewardText` = 'I knew that you had it in you, kid. You\'ve got the look of someone who knows what $g he : she; likes. Specifically that you like pleasing me and the powers that be. And that you have, I guarantee.$B$BHaha, ok, I\'ll just get these fish properly stashed away, and then you and I can have a little talk concerning you collecting another twenty albacore.' WHERE `ID` = 8525;
UPDATE `quest_offer_reward` SET `RewardText` = 'Well, I guess that looks like the right number of tin bars. Don\'t try to fool me, $c! Counting makes my skull hurt. Now I go and put these bars on the stack and you go out and bring me back more of the same.' WHERE `ID` = 8542;
UPDATE `quest_offer_reward` SET `RewardText` = 'And so our efforts push us that much closer to war. Thank you for your hard work in gathering this peacebloom $c. I assure you that it will go to good use, and that your contribution has been noted $N. Should you find yourself willing, please return to me again with more of the flowers. Until then, may the Earth Mother guide you.' WHERE `ID` = 8549;
UPDATE `quest_offer_reward` SET `RewardText` = '$C! Pele\'keiki happy for now. Pele\'keiki take all that firebloom and put it in box so it stay fresh. Pele\'keiki be seein\' to it that all the firebloom bein\' made into good stuff for the war. And if you be gettin\' anymore, you come see Pele\'keiki fast. Pele\'keiki prolly be needin\' more.' WHERE `ID` = 8580;
UPDATE `quest_offer_reward` SET `RewardText` = 'A commendable effort, $c. I will measure these specimens for their appropriate usage and note your contribution. The purple lotus will then need to be properly stored until I am ready for them. As for you, if you are still available I should imagine that I\'ll still need more purple lotus. Please check back with me in a moment.' WHERE `ID` = 8582;
UPDATE `quest_offer_reward` SET `RewardText` = 'Oh, so you do have the heavy leather I needed. Your blade is sharp indeed, $c; these are good skins! Now that we\'ve gotten off on the right foot with one another I\'ll make sure that your contribution is put to good use. And if you happen to come across more heavy leather, bring it my way.' WHERE `ID` = 8588;
UPDATE `quest_offer_reward` SET `RewardText` = 'You have my thanks, $c, and the gratitude of the Horde. If you come across more wool bandages bring them to me here should you wish to further contribute to the war effort. Until then, may your ancestors watch over you!' WHERE `ID` = 8604;
UPDATE `quest_offer_reward` SET `RewardText` = 'You are a credit to the Horde, $c. Thank you for your efforts; they are appreciated! I\'ll have to pack these fresh bandages away and take another count to see how far along we are to our goal. If you\'d like you could gather more runecloth bandages and return them to me here.' WHERE `ID` = 8609;
UPDATE `quest_offer_reward` SET `RewardText` = 'Ok, this stack of meat looks good to me. I\'ll salt them, and then pack them away and hopefully they\'ll keep fresh enough to be edible when the time comes.$B$BThanks for the contribution, $c. Do you think you could bring me another rack?' WHERE `ID` = 8611;
UPDATE `quest_offer_reward` SET `RewardText` = 'Oh ya, this be the good stuff. I pack it up real nice so it not go to waste. Thanks be to you for helpin\' me out like this. I\'m thinkin\' you an A-number-one fisherman for all this spotted yellowtail. An if you happen to fish up and cook even more, you bring it to me here; I make sure everyone know you did!' WHERE `ID` = 8613;
