name: core-build
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
    branches:
      - 'master'
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    if: !github.event.pull_request.draft
    uses: azerothcore/reusable-workflows/.github/workflows/core_build_modules.yml@main
    with:
      module_repo: ${{ github.event.repository.name }}
